# Site settings
name: Jason Carpenter
description: "Jason Carpenter - Full Stack Software Developer"
url: "http://jasoncarpenter.me"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  Jason9199
# codepen_username: your_codepen_username_goes_here
facebook_username: jason.carpenter.378
# vk_username: your_vk_username_goes_here
twitter_username: JasonWCarpenter
# google_plus_username: your_google_plus_username_goes_here
linkedin_username: jasoncarpenter2
# vine_username:  your_vine_username_goes_here
# instagram_username:  your_instagram_username_goes_here
# flickr_username: your_flickr_username_goes_here
# steam_username: your_steam_username_goes_here
# soundcloud_username:  your_soundcloud_username_goes_here
# stack_of_username: your_stack_overflow_account_id_number_goes_here
# reddit_username: your_reddit_username_goes_here
# medium_username:  your_medium_username_goes_here
# tumblr_username: your_tumblr_username_goes_here
# weibo_username: your_weibo_username_goes_here
# lastfm_username: your_lastfm_username_goes_here
# blog_url: "/blog"
email: jason9199@gmail.com
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/7329526"


# front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


front_video: yes
front_video_mp4: yes
front_video_path_mp4: "video/background.mp4"
front_video_webm: yes
front_video_path_webm: "video/background.webm"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty